### PR TITLE
P.Bas. 1

### PR DESCRIPTION
**Pull request by samosafuz**
This series of commits updates and organizes the loose `p.bas;;*.xml` files into `p.bas;1;*`

The idnos, titles, filenames, reprint-from and reprint-in links and info have all been updated.

I will update the checklist link to `p.bas;;` >> `p.bas;1;` via a separate pull in the sitedocs repo

### CODE REVIEW

**Comment by samosafuz** [comment]
Addresses #214.

GitHub is telling me there's a conflict that needs resolving, but won't show it to me. @jcowey, can you see what it is?

**Comment by jcowey** [comment]
@samosafuz no I cannot see what is wrong. I am puzzled. Have requested a review from @hcayless.

**Comment by jcowey** [comment]
Looks as if it is this merge which may be causing the problem. 
https://github.com/papyri/idp.data/commit/04d54186fc2395e4cc40a1f5c7404bf20dcbea6b

**Comment by samosafuz** [comment]
I've added `rend="indent"` in line 12, but GitHub still reports a conflict.

**Comment by jcowey** [comment]
Very strange

**Comment by jcowey** [comment]
https://github.com/papyri/idp.data/blob/f6b864054aa3546f444f14ebc98556a1ded97073/DDB_EpiDoc_XML/p.bas/p.bas.1/p.bas.15.xml#L14-L16

```
            <idno type="filename">p.bas.15</idno>
            <idno type="ddb-perseus-style">0070;;15</idno>
            <idno type="ddb-hybrid">p.bas;;15</idno>

```            

look wrong

```
            <idno type="filename">p.bas.1.15</idno>
            <idno type="ddb-perseus-style">0070;;15</idno>
            <idno type="ddb-hybrid">p.bas;1;15</idno>

```

Is it that?

**Comment by samosafuz** [comment]
Those are idno changes that my pull addresses; if they were causing the conflict, then every affected file would be triggering conflicts, too. I'll try to look through the file history a bit more later on.

**Comment by hcayless** [comment]
I was able to merge the PR via the command line without issue.

**Pull request merged**
