### PR TITLE
Add print translations from P.Oxy. 1

### PR DESCRIPTION
**Pull request by ryanfb**
This adds print translations from https://archive.org/details/oxyrhynchuspapyr01gren

### CODE REVIEW

**Comment by jcowey** [comment]
May I suggest that you put the attribution of the translation in a `note`. That is what I have been doing in the last few months. E.g. https://github.com/papyri/idp.data/blob/master/HGV_trans_EpiDoc/19729.xml#L70
```
<note>Translation: Law in Social Networks Project (Warsaw)</note>
``` 
I have been putting it at the end of the translation. Positioning does not really matter. By putting it in a `note`  I am hoping that when we revisit the whole question of attribution the data will at least be more machine manageable. Otherwise there will be lots of nasty parsing is my fear.

**Comment by jcowey** [comment]
Otherwise I will be delighted to push this through. The translations look fine. Did you OCR? I am certainly not going to check each one.

**Comment by ryanfb** [comment]
> May I suggest that you put the attribution of the translation in a note. That is what I have been doing in the last few months.

No problem, I'll make a commit changing the attribution then go ahead and merge afterwards.

> The translations look fine. Did you OCR? I am certainly not going to check each one.

Yes, I re-OCR'd with [ocrmypdf](https://ocrmypdf.readthedocs.io/en/latest/index.html) (a convenient wrapper around Tesseract), then copied and reviewed the translations in a workflow I developed. So, there's no additional text division metadata, but there are at least translations.

I plan on working through the rest of the public domain P.Oxy. volumes in the same way, and then moving on to work through any translations available from the rest of the public domain and open access volumes in the Checklist of Editions. I think even P.Oxy. alone may nearly double the number of translations we have in `HGV_trans_EpiDoc`.

**Comment by jcowey** [comment]
Great. Thanks.

**Comment by jcowey** [comment]
Saw you opened a DCLP file, Ryan. Translations for them all go into the same repository: https://github.com/papyri/idp.data/tree/master/HGV_trans_EpiDoc

Maybe that was what you were looking at.

**Comment by ryanfb** [comment]
Yes, there's one translation in this batch that only has a DCLP record (= `HGV_trans_EpiDoc/63934.xml`), so I wanted to double-check and see that I was getting the `<idno>`'s correct. I may go back later through the P.Oxy. volumes for a second pass on adding literary papyri (for now I'm mostly focusing on papyri that have a DDbDP record).

**Pull request merged**
