### PR TITLE
Update 62499.xml

### PR DESCRIPTION
**Pull request by danielrruf**
Many instances of `<supplied reason="lost"><supplied reason="lost">BHHHH</supplied></supplied>` reduced to its natural expression

### CODE REVIEW

**Comment by jcowey** [comment]
@HolgerEssler can you please check to see whether I am right about these double square brackets should in fact be deleted brackets.

**Comment by HolgerEssler** [comment]
Most of them are indeed double square brackets used erroneously to indicate deleted text, but there are some instances where we have a nesting of ```<supplied evidence="parallel" reason="lost"><supplied reason="lost">``` closing with ```</supplied></supplied>```. In these cases the patch deletes one of the two closing tags while leaving the corresponding part untouched - which produces unvalid xml (hence the failed validation above).

**Comment by jcowey** [comment]
@HolgerEssler so what to do? Can you produce a patch for this file and then Daniel could retire this issue?

**Comment by HolgerEssler** [comment]
I can correct the xml, but it will take some time because of other deadlines. In any case, we should remind Daniel to make pull requests only when the patches pass all tests.

**Comment by danielrruf** [comment]
Thanks for the reminder, Holger. I stand corrected. It’s anything I can do to solve the issue?

Enviado desde mi iPhone

**Pull request closed without merging**
