### PR TITLE
Update 62499.xml

### PR DESCRIPTION
**Pull request by danielrruf**

### CODE REVIEW

**Comment by jcowey** [comment]
@HolgerEssler can you give your opinion on this too please.

**Comment by HolgerEssler** [comment]
Again same file as in #232 and #239, but this time deleting also the nested ```<supplied evidence="parallel" reason="lost"><supplied reason="lost">```. xml is valid now, but even more information is lost. I suggest Daniel withdraws all three patches and I correct the xml.

**Comment by jcowey** [comment]
@danielrruf Hello Daniel, would you please look at the comments on #232, #239 and #240. It seems best to Holger and me that you withdraw all three of these pull requests. 
And for your information it seems that double square brackets often have to be looked at closely. They have sometimes been encoded where deletion brackets were intended.

**Comment by danielrruf** [comment]
Duly complied. Please forgive any inconvenience!

Enviado desde mi iPhone

**Pull request closed without merging**
